In [144]:
#important imports
import os
import numpy as np
import pandas as pd
from scipy.misc import imread
import imageio
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split


In [ ]:
#convert image data into dataset
root_dir = os.getcwd()
img_dir = os.path.join(root_dir, 'dataset/Test/digits')

pixels = np.array(['pixel_{:04d}'.format(x) for x in range(1024)])
flag = True

for char_name in sorted(os.listdir(img_dir)):
    char_dir = os.path.join(img_dir, char_name)
    img_df = pd.DataFrame(columns=pixels)
    
    for img_file in sorted(os.listdir(char_dir)):
        image = pd.Series(imageio.imread(os.path.join(char_dir, img_file)).flatten(), index=pixels)
        img_df = img_df.append(image.T, ignore_index=True)
        
    img_df = img_df.astype(np.uint8)
    img_df['character'] = char_name
    
    img_df.to_csv('train_digits_data.csv', index=False, mode='a', header=flag)
    flag=False
    
    print('*', end='')

In [145]:
#Loading the data
data = pd.read_csv("./train_digits_data.csv")
data.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   pixel_0006  pixel_0007  pixel_0008  pixel_0009    ...      pixel_1015  \
0           0           0           0           0    ...               0   
1           0           0           0           0    ...               0   
2           0           0           0           0    ...               0   
3           0           0           0           0    ...               0   
4           0           0           0           0    ...               0   

   pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  pixel_1021  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   pixel_1022  pixel_1023  character  
0           0           0    digit_0  
1           0           0    digit_0  
2           0           0    digit_0  
3           0           0    digit_0  
4           0           0    digit_0  

[5 rows x 1025 columns]

In [146]:
#shuffling
from sklearn.utils import shuffle
data = shuffle(data)
data.head()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
14118           0           0           0           0           0           0   
9249            0           0           0           0           0           0   
4671            0           0           0           0           0           0   
3439            0           0           0           0           0           0   
12126           0           0           0           0           0           0   

       pixel_0006  pixel_0007  pixel_0008  pixel_0009    ...      pixel_1015  \
14118           0           0           0           0    ...               0   
9249            0           0           0           0    ...               0   
4671            0           0           0           0    ...               0   
3439            0           0           0           0    ...               0   
12126           0           0           0           0    ...               0   

       pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  pixel_1021  \
14118           0           0           0           0           0           0   
9249            0           0           0           0           0           0   
4671            0           0           0           0           0           0   
3439            0           0           0           0           0           0   
12126           0           0           0           0           0           0   

       pixel_1022  pixel_1023  character  
14118           0           0    digit_8  
9249            0           0    digit_5  
4671            0           0    digit_2  
3439            0           0    digit_2  
12126           0           0    digit_7  

[5 rows x 1025 columns]

In [147]:
#convert label characters into label 0-9(int)
data['character_class'] = LabelEncoder().fit_transform(data.character)
data.drop('character', axis=1, inplace=True)
data = data.astype(np.uint8)

In [148]:
data.shape

(17000, 1025)

In [149]:
data.tail()

pixel_0000  pixel_0001  pixel_0002  pixel_0003  pixel_0004  pixel_0005  \
1519            0           0           0           0           0           0   
7935            0           0           0           0           0           0   
11385           0           0           0           0           0           0   
3721            0           0           0           0           0           0   
14224           0           0           0           0           0           0   

       pixel_0006  pixel_0007  pixel_0008  pixel_0009       ...         \
1519            0           0           0           0       ...          
7935            0           0           0           0       ...          
11385           0           0           0           0       ...          
3721            0           0           0           0       ...          
14224           0           0           0           0       ...          

       pixel_1015  pixel_1016  pixel_1017  pixel_1018  pixel_1019  pixel_1020  \
1519            0           0           0           0           0           0   
7935            0           0           0           0           0           0   
11385           0           0           0           0           0           0   
3721            0           0           0           0           0           0   
14224           0           0           0           0           0           0   

       pixel_1021  pixel_1022  pixel_1023  character_class  
1519            0           0           0                0  
7935            0           0           0                4  
11385           0           0           0                6  
3721            0           0           0                2  
14224           0           0           0                8  

[5 rows x 1025 columns]

In [152]:
X = (data.values[:,:-1]/255.0* 0.99) + 0.01
x0=np.ones([len(X),1])
X=np.concatenate((x0,X),axis=1)
Y = data["character_class"].values.reshape(-1,1)

In [154]:
print("X is:",X)
print("shape of X:",X.shape)
print("Y is:",Y)
print("shape of Y:",Y.shape)

X is: [[1.   0.01 0.01 ... 0.01 0.01 0.01]
 [1.   0.01 0.01 ... 0.01 0.01 0.01]
 [1.   0.01 0.01 ... 0.01 0.01 0.01]
 ...
 [1.   0.01 0.01 ... 0.01 0.01 0.01]
 [1.   0.01 0.01 ... 0.01 0.01 0.01]
 [1.   0.01 0.01 ... 0.01 0.01 0.01]]
shape of X: (17000, 1025)
Y is: [[8]
 [5]
 [2]
 ...
 [6]
 [2]
 [8]]
shape of Y: (17000, 1)


In [203]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=1000, stratify=Y)
print("X_train shape",X_train.shape)
print("X_test shape",X_vald.shape)
print("y_train shape",y_train.shape)
print("y_test shape",y_vald.shape)

X_train shape (13600, 1025)
X_test shape (3400, 1025)
y_train shape (13600, 1)
y_test shape (3400, 1)


In [156]:
# Main Logistic Regression Equations

# sigmoid function
def sigmoid(z) :  
    return 1.0/(1.0 + np.exp(-z))

# Model function
def hypothesis_logistic(X,w) : 
    return sigmoid(np.dot(X,w))

# Cost Function
def J(X,w,y) : 
    m = y.size
    return -(np.sum(np.log(hypothesis_logistic(X,w))) + np.dot((y-1).T,(np.dot(X,w))))/m

# Cost Function with Regularization
def J_reg(X,w,y,reg_lambda) : 
    m = y.size
    return J(X,w,y) + reg_lambda/(2.0*m) * np.dot(w[1:],w[1:])

# Gradient of Cost Function
def gradJ(X,w,y) : 
    m = y.size
    return (np.dot(X.T,(hypothesis_logistic(X,w) - y)))/m

# Gradient of Cost Function with Regularization
def gradJ_reg(X,w,y,reg_lambda) : 
    m = y.size
    return gradJ(X,w,y) + reg_lambda/(2.0*m) * np.concatenate(([0], w[1:])).T


In [170]:
def optimize_Weight(X,w,y,lr,iterations):
    for i in range(iterations):
            w = w - (lr * gradJ(X,w,y))
            cost = J(X,w,y)
            if(i%1000==0):
                print('Cost at iteration:%s'%i,cost)
    return w, cost

In [127]:
wt = np.zeros((1,len(X_train[0,:]))).reshape(-1,1)
print(wt)
wt.shape

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


(1025, 1)

In [171]:
num_class=10
wt_list=[]
def multiclass_1vsall(X,y):
    for i in range(num_class):
        wt = np.zeros((1,len(X_train[0,:]))).reshape(-1,1)
        #The Current item is: %s" % item
        print("Learning one vs all at class_label:%s" %i)
        y_t = (y_train == float(i)).astype(int)
        w_optimized,cost = optimize_Weight(X_train,wt,y_t,0.001,10000)
        wt_list.append(w_optimized.flatten())
    return wt_list

In [172]:
#train to minimize cosst
optimized_weight = multiclass_1vsall(X_train,y_train)

Learning one vs all at class_label:0
Cost at iteration:0 [[0.67752969]]
Cost at iteration:1000 [[0.15941566]]
Cost at iteration:2000 [[0.11799438]]
Cost at iteration:3000 [[0.09932223]]
Cost at iteration:4000 [[0.08835175]]
Cost at iteration:5000 [[0.08095051]]
Cost at iteration:6000 [[0.07552452]]
Cost at iteration:7000 [[0.07132185]]
Cost at iteration:8000 [[0.06793781]]
Cost at iteration:9000 [[0.06513342]]
Learning one vs all at class_label:1
Cost at iteration:0 [[0.67915337]]
Cost at iteration:1000 [[0.14298674]]
Cost at iteration:2000 [[0.10057921]]
Cost at iteration:3000 [[0.08270479]]
Cost at iteration:4000 [[0.07232613]]
Cost at iteration:5000 [[0.06532201]]
Cost at iteration:6000 [[0.06017319]]
Cost at iteration:7000 [[0.05617581]]
Cost at iteration:8000 [[0.05295309]]
Cost at iteration:9000 [[0.05028223]]
Learning one vs all at class_label:2
Cost at iteration:0 [[0.67831935]]
Cost at iteration:1000 [[0.2203569]]
Cost at iteration:2000 [[0.18646558]]
Cost at iteration:3000 [[

In [174]:
all_theta =np.array(optimized_weight)
print(all_theta)
all_theta.shape

[[-0.04953267 -0.00049533 -0.00049533 ... -0.00049533 -0.00049533
  -0.00049533]
 [-0.14409652 -0.00144097 -0.00144097 ... -0.00144097 -0.00144097
  -0.00144097]
 [-0.10347016 -0.0010347  -0.0010347  ... -0.0010347  -0.0010347
  -0.0010347 ]
 ...
 [-0.18689332 -0.00186893 -0.00186893 ... -0.00186893 -0.00186893
  -0.00186893]
 [-0.12145077 -0.00121451 -0.00121451 ... -0.00121451 -0.00121451
  -0.00121451]
 [-0.19288874 -0.00192889 -0.00192889 ... -0.00192889 -0.00192889
  -0.00192889]]


(10, 1025)

In [263]:
prob_matrix = X_test.dot(all_theta.T)
print(prob_matrix)
prob_matrix.shape

[[ 1.27180077 -2.36728518 -3.03180223 ... -1.73801817 -2.56191809
  -3.37836639]
 [-4.16632965 -5.71038821  1.0686992  ... -4.25545636 -2.02294761
  -5.96438215]
 [-3.30245416 -5.92495049 -4.63725884 ...  4.06562115 -7.43256167
  -5.15217619]
 ...
 [-3.25446968 -4.19995913 -7.05629336 ... -0.0658528  -7.83516349
  -4.82973451]
 [ 2.59718509 -4.41116267 -4.52089719 ... -1.79399363 -2.44827573
  -2.51866019]
 [-7.08614389 -6.93274984 -3.65847132 ... -4.22507619 -7.16884415
  -2.34307881]]


(3400, 10)

In [264]:
#method-1
# p = np.empty((len(prob_matrix)))

# for i in range(0, len(prob_matrix)):    
#     idx = np.argmax(prob_matrix[i])
#     print(idx)
    
#     #reverse map index 0
#     if(idx == 0):
#         p[i] = 10
#     else:
#         p[i] = idx

0
2
7
1
9
3
4
3
6
7
5
2
3
7
4
9
2
7
5
2
5
3
6
4
9
7
4
1
3
6
0
9
5
9
7
9
0
4
9
5
6
0
4
0
4
1
4
4
5
6
4
5
3
4
9
0
1
1
2
7
7
6
8
4
2
8
4
0
1
2
4
7
0
9
0
4
1
9
5
9
3
4
9
1
6
1
8
7
7
5
2
9
1
6
1
4
2
7
6
5
5
2
1
0
6
0
2
3
6
6
7
0
2
9
3
6
6
1
9
4
6
2
9
3
3
7
2
0
7
2
1
1
2
3
6
8
8
8
9
0
8
4
0
7
5
0
2
1
8
8
0
8
5
8
0
1
0
4
3
0
4
0
5
3
8
0
1
4
4
3
5
2
0
6
7
4
1
2
5
7
2
8
6
3
8
4
4
0
2
8
0
7
3
5
3
6
3
9
8
8
9
1
6
8
4
2
2
2
2
1
1
9
4
7
5
4
7
7
6
4
7
9
1
4
6
4
8
4
4
2
7
6
1
8
7
0
0
3
7
7
8
4
6
8
0
0
3
5
9
4
7
7
1
7
7
6
8
2
6
6
4
2
2
0
0
5
0
7
3
8
9
1
8
6
6
8
3
8
0
1
8
2
7
8
6
8
8
7
4
4
7
2
2
5
9
0
0
1
2
3
5
7
2
8
7
9
8
3
1
5
7
9
0
4
2
9
0
2
2
7
1
2
9
0
6
3
6
2
3
0
3
8
7
8
4
3
6
6
9
3
5
1
4
4
6
1
0
4
2
0
6
9
7
0
9
5
7
5
6
7
9
9
2
2
0
9
0
5
4
4
3
5
0
3
8
7
2
8
5
4
7
8
4
1
3
1
2
8
9
4
5
4
1
2
5
6
6
2
5
8
0
5
2
4
0
6
2
3
5
2
0
1
0
2
1
3
0
6
9
0
5
7
8
3
5
3
0
9
7
3
4
2
3
8
1
4
6
1
8
0
6
5
5
1
7
0
7
1
5
7
3
8
0
5
5
0
8
3
1
1
8
1
9
9
7
6
4
8
9
5
4
9
1
6
3
9
9
7
5
7
9
5
5
6
1
9
5
2
1
5
6
7
4
5
4
4
1
5
2
3


In [265]:
# p = np.reshape(p, (len(p), 1))
# print(p)
# p.shape

[[10.]
 [ 2.]
 [ 7.]
 ...
 [ 7.]
 [10.]
 [ 3.]]


(3400, 1)

In [266]:
# accuracy=np.mean(((p == y_test) *100))
# accuracy

80.55882352941177

In [267]:
def predictOneVsAll(all_theta, X):

    m = X.shape[0]
    num_labels = all_theta.shape[0]

    p = np.zeros((m, 1))
    p = np.argmax(sigmoid( np.dot(X,all_theta.T) ), axis=1)
    return p

In [249]:
y_pred = predictOneVsAll(all_theta, X_test)
print(y_pred)
y_pred.shape

[0 2 7 ... 7 0 3]


(3400,)

In [250]:
y_pred = np.reshape(y_pred, (len(y_pred), 1))

In [251]:
print(y_pred)

[[0]
 [2]
 [7]
 ...
 [7]
 [0]
 [3]]


In [252]:
accuracy=np.mean((y_(pred == y_test) *100))
accuracy

90.05882352941177

In [269]:
def calculate_recall_precision(label, prediction):
    true_positives = 0
    false_positives = 0
    true_negatives = 0
    false_negatives = 0
 
    for i in range(0, len(label)):
        if prediction[i] == 1:
            if prediction[i] == label[i]:
                true_positives += 1
            else:
                false_positives += 1
        else:
            if prediction[i] == label[i]:
                true_negatives += 1
            else:
                false_negatives += 1
 
    # accuracy
    accuracy = (true_positives + true_negatives) \
               / (true_positives + true_negatives + false_positives + false_negatives)
 
    # precision 
    precision = true_positives / (true_positives + false_positives)
    # recall 
    recall = true_positives / (true_positives + false_negatives)
 
    #f1_score
    f1_score = 2 / ((1 / precision) + (1 / recall))
 
    return accuracy, precision, recall, f1_score
 
 
accuracy, precision, recall, f1_score = calculate_recall_precision(y_test, pred)
 
print("Accuracy: ", accuracy*100)
print("Precision: ", precision*100)
print("Recall: ", recall*100)
print("F1 score: ", f1_score*100)

Accuracy:  90.05882352941177
Precision:  93.22033898305084
Recall:  51.24223602484472
F1 score:  66.13226452905812
